### ISSUE TITLE
Albedo not used in calculations?

### ISSUE THREAD

**Issue by iancrossfield** [exoclime/HELIOS#4]
Unless I'm missing something, it seems that the base code never uses the 'albedo' parameter that is settable in 'param.dat' (and that is stored in 'quant.surf_albedo').  For example, the calculation below, of the planet's equilibrium temperature, should (I think!) include an additional factor of `(1. - quant.surf_albedo)**0.25` to account for the albedo.

`        T_eff = (1.0-quant.dir_beam) * quant.f_factor ** 0.25 * (quant.R_star / quant.a) ** 0.5 * quant.T_star \
                + quant.dir_beam * abs(quant.mu_star) ** 0.25 * (quant.R_star / quant.a) ** 0.5 * quant.T_star
`

**Comment by matejmalik** [comment]
Thanks for checking the equations! 

Although they are used somewhat ambiguously in literature, I distinguish between the "equilibrium" temperature and the "effective" temperature. Let me try to explain my perspective.

In the shown equation the "effective" temperature is calculated. I define the effective temperature  as the temperature the planet would have if it were a perfect blackbody, which means a zero albedo. This is a definition that (I think) stems from the stellar community, because one commonly describes stars as blackbodies of a given effective temperature. For exoplanets I think it makes sense to use the effective temperature because there is no way we can determine the true albedo of the planet. For me, the effective temperature is not a realistic temperature found at the planetary surface or in the atmosphere, but merely a handy proxy for the total amount of emitted flux. 

I agree that the "equilibrium" temperature does include the planetary albedo. This albedo is defined as the ratio of the reflected stellar irradiation over the total incoming stellar irradiation at TOA. The planetary albedo is in fact not being calculated in HELIOS. This is because once the stellar flux is scattered it is added to the "diffuse" flux, which also contains the thermal emission. Thus it is impossible to separate the reflected stellar flux from the planetary emission. If one is interested in the TOA albedo, one can still calculate it by post-processing a planet with the star "switched off" and then subtract the calculated TOA flux (which is only thermal emission now) from the regular planet + star run. Since the planetary albedo is not calculated I avoid using the equilibrium temperature in the code (because it is unknown).

The code variable "quant.surf_albedo" describes the surface albedo. This is the albedo of the surface, located at the BOA. In the current version of the code this is simply given by a constant number, describing a constant reflectivity over all wavelengths. The surface albedo is used in the code to calculate the the amount of absorbed and reflected flux at the surface (bottom-most interface in the numerical grid). In the code this calculation can be found in the file "kernels.cu", lines 1616 - 1621.

I hope I could clarify the procedures used in HELIOS. Please let me know if you still think there are issues in the calculations.

**Comment by iancrossfield** [comment]
@matejmalik - Got it, thanks. I think the use of 'surface' albdeo will be clear to people working on rocky planets (which have surfaces), but may be slightly confusing to people like me working on gas planets (where we're sometimes used to defining an ad-hoc albedo value). But it sounds like HELIOS self-consistently takes the albedo into account; just something for me to keep in mind.
